# Generated by Django 5.1.1 on 2025-08-23 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('rooms', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('BE', 'Booking Engine'), ('IN_HOUSE', 'In-house'), ('OTA_BOOKING', 'Booking.com'), ('OTA_EXPEDIA', 'Expedia'), ('OTHER', 'Other')], default='BE', max_length=20)),
                ('source_ref', models.CharField(blank=True, default='', max_length=120)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=120)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests_adults', models.PositiveIntegerField(default=2)),
                ('guests_children', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('held', 'Held'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='pending', max_length=20)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tenants.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.tenant')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='reservations.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=120)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='tenants.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='rooms.roomtype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BookingNight',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nights', to='reservations.booking')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_nights', to='rooms.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_nights', to='rooms.roomtype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'date'], name='reservation_tenant__66fe6c_idx')],
                'unique_together': {('tenant', 'booking', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChannelMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ota', models.CharField(choices=[('BOOKING', 'Booking.com'), ('EXPEDIA', 'Expedia'), ('OTHER', 'Other')], max_length=20)),
                ('ota_hotel_id', models.CharField(max_length=80)),
                ('ota_room_code', models.CharField(max_length=80)),
                ('ota_rate_code', models.CharField(blank=True, default='', max_length=80)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_mappings', to='rooms.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_mappings', to='rooms.roomtype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'ota'], name='reservation_tenant__83d2fe_idx')],
                'unique_together': {('tenant', 'ota', 'ota_hotel_id', 'ota_room_code', 'ota_rate_code')},
            },
        ),
        migrations.CreateModel(
            name='ChannelReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ota', models.CharField(max_length=20)),
                ('ota_reservation_id', models.CharField(max_length=80)),
                ('payload_json', models.JSONField()),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_reservation', to='reservations.booking')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'ota'], name='reservation_tenant__da1cfe_idx')],
                'unique_together': {('tenant', 'ota', 'ota_reservation_id')},
            },
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['tenant', 'email'], name='reservation_tenant__9e1543_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'property', 'check_in'], name='reservation_tenant__13e144_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'status'], name='reservation_tenant__abbf9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_booking_idempotency'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['tenant', 'date'], name='reservation_tenant__07976b_idx'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['tenant', 'expires_at'], name='reservation_tenant__016dd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hold',
            unique_together={('tenant', 'room_type', 'date', 'idempotency_key')},
        ),
    ]
